# debug / info / warning / error / silent
loglevel: info

# URL format: [protocol://]host[:port]
proxy: socks5://192.168.1.1:2000

# URL format: [driver://]name
device: tun://tun_3000

# Maximum transmission unit for each packet
mtu: 1500

# Timeout for each UDP session, default value: 60 seconds

udp-timeout: 120s
